apiVersion: v1
kind: Service
metadata: 
  name: productcatalogue
  labels: 
    name: productcatalogue
spec:
  ports:
    - name: http
      port: 8020
  selector: 
    name: productcatalogue
    version: "1.0.40"
