apiVersion: v1
kind: Service
metadata: 
  name: shopfront
  labels: 
    name: shopfront
spec:
  externalIPs:
  - 192.168.5.173
  ports:
    - name: http
      port: 80
      targetPort: 8010
  selector: 
    name: shopfront
    version: "1.0.40"
  type: LoadBalancer
