apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: mysql
spec:
  template:
     metadata: 
          labels:
            app: mysql

     spec:
       containers:
             - name: mysqlmy  
               image: rishabh050189/mysqlmy:02
               imagePullPolicy: Always
               ports:
                - containerPort: 3306
               env:
                - name: Mysql_Root_Password
                  value: password
