apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: wordpress
spec: 
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec: 
      containers: 
        - name: wordpressmy 
          image: "rishabh050189/wordpressmy:01"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
           - name: Wordpress_Password
             value: passsword
